export const ADD_ITEM_TO_CART_REQUEST = "ADD_ITEM_TO_CART_REQUEST";
export const ADD_ITEM_TO_CART_SUCCESS = "ADD_ITEM_TO_CART_SUCCESS";
export const ADD_ITEM_TO_CART_FAIL = "ADD_ITEM_TO_CART_FAIL";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
